-- Family Foundation V1 (Family tier, multi-profile membership only —
-- NOT shared health-data visibility, NOT challenges/goals, see
-- routers/family.py docstring). Non-destructive: only creates 2 new
-- tables + indexes. Does not alter any existing table. NOT yet run in
-- Supabase.
--
-- No RLS is used anywhere in this schema (access control is enforced
-- entirely at the FastAPI layer via core/auth.py::require_user, same as
-- every other Twin Intelligence table since migration 003/024) — both new
-- tables explicitly disable it for consistency, not because it was ever
-- enabled by default.

create table if not exists public.vt_families (
  id bigint generated by default as identity primary key,
  owner_user_id bigint not null references public.vt_users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.vt_families disable row level security;

create table if not exists public.vt_family_members (
  id bigint generated by default as identity primary key,
  family_id bigint not null references public.vt_families(id) on delete cascade,
  user_id bigint not null references public.vt_users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner', 'member')),
  status text not null default 'invited' check (status in ('active', 'invited', 'removed', 'left')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (family_id, user_id)
);

-- A user may belong to at most ONE family at a time in an active/invited
-- state (Constitution-adjacent product rule: no conflicting Family groups)
-- — enforced here at the database level, not just in application code, via
-- a partial unique index. A user with only 'removed'/'left' rows is free to
-- join a (or another) family again.
create unique index if not exists idx_vt_family_members_one_open_membership_per_user
  on public.vt_family_members(user_id)
  where status in ('active', 'invited');

create index if not exists idx_vt_family_members_family_id on public.vt_family_members(family_id);

alter table public.vt_family_members disable row level security;

notify pgrst, 'reload schema';
