-- Family Goals V1 ("Familienziele", Family tier only, see
-- routers/family.py module docstring). Non-destructive: only creates 2 new
-- tables + indexes. Does not alter any existing table, including
-- vt_wellness_goals (personal goals stay a completely separate system —
-- Family Goals are shared coordination goals, never private wellness
-- data). NOT yet run in Supabase.
--
-- No RLS (same as every other table in this schema — enforcement is
-- entirely at the FastAPI layer via core/auth.py::require_user).

create table if not exists public.vt_family_goals (
  id bigint generated by default as identity primary key,
  family_id bigint not null references public.vt_families(id) on delete cascade,
  created_by_user_id bigint not null references public.vt_users(id) on delete cascade,
  title text not null,
  description text,
  target_type text not null default 'count' check (target_type in ('count', 'days', 'custom')),
  target_value numeric,
  start_date date,
  end_date date,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_vt_family_goals_family_id on public.vt_family_goals(family_id);

alter table public.vt_family_goals disable row level security;

create table if not exists public.vt_family_goal_members (
  id bigint generated by default as identity primary key,
  family_goal_id bigint not null references public.vt_family_goals(id) on delete cascade,
  user_id bigint not null references public.vt_users(id) on delete cascade,
  progress_value numeric not null default 0,
  completed boolean not null default false,
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (family_goal_id, user_id)
);

create index if not exists idx_vt_family_goal_members_goal_id on public.vt_family_goal_members(family_goal_id);
create index if not exists idx_vt_family_goal_members_user_id on public.vt_family_goal_members(user_id);

alter table public.vt_family_goal_members disable row level security;

notify pgrst, 'reload schema';
