-- Family Challenges V1 ("Familien-Challenges", Family tier only, see
-- routers/family.py module docstring). Non-destructive: only creates 2 new
-- tables + indexes. Deliberately a SEPARATE system from vt_family_goals
-- (kept apart per explicit task instruction even though the shape is
-- similar today) — Family Challenges are time-boxed shared motivation
-- activities (e.g. "7 Tage gemeinsam spazieren") with their own
-- target_type vocabulary (completion_count/days_completed), distinct from
-- Family Goals' open-ended coordination targets. Never touches any
-- private wellness table. NOT yet run in Supabase.
--
-- No RLS (same as every other table in this schema — enforcement is
-- entirely at the FastAPI layer via core/auth.py::require_user).

create table if not exists public.vt_family_challenges (
  id bigint generated by default as identity primary key,
  family_id bigint not null references public.vt_families(id) on delete cascade,
  created_by_user_id bigint not null references public.vt_users(id) on delete cascade,
  title text not null,
  description text,
  target_type text not null default 'completion_count' check (target_type in ('completion_count', 'days_completed')),
  target_value numeric check (target_value is null or target_value >= 0),
  start_date date,
  end_date date,
  status text not null default 'active' check (status in ('active', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_vt_family_challenges_family_id on public.vt_family_challenges(family_id);

alter table public.vt_family_challenges disable row level security;

create table if not exists public.vt_family_challenge_members (
  id bigint generated by default as identity primary key,
  family_challenge_id bigint not null references public.vt_family_challenges(id) on delete cascade,
  user_id bigint not null references public.vt_users(id) on delete cascade,
  progress_value numeric not null default 0 check (progress_value >= 0),
  completed boolean not null default false,
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (family_challenge_id, user_id)
);

create index if not exists idx_vt_family_challenge_members_challenge_id on public.vt_family_challenge_members(family_challenge_id);
create index if not exists idx_vt_family_challenge_members_user_id on public.vt_family_challenge_members(user_id);

alter table public.vt_family_challenge_members disable row level security;

notify pgrst, 'reload schema';
